name: CI/CD for Laravel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, xml, curl

      # Ahora se especifica el directorio completo para el comando composer
      - name: Install dependencies
        run: |
          cd example-app
          composer install --no-interaction --prefer-dist

      - name: Run PHPUnit tests
        run: |
          cd example-app
          php artisan key:generate
          php artisan migrate --env=testing
          ./vendor/bin/phpunit --coverage-text

          