name: CI/CD for Laravel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, bcmath, xml, curl

      - name: Install dependencies
        run: |
          composer install --no-interaction --prefer-dist

      - name: Run PHPUnit tests
        run: |
          php artisan key:generate
          php artisan migrate --env=testing
          ./vendor/bin/phpunit --coverage-text

      - name: Deploy to production (Optional)
        run: |
          echo "Deploying to production server"
          # Aquí puedes agregar comandos para tu despliegue
          # Por ejemplo, si usas SSH para conectarte al servidor:
          # ssh -o StrictHostKeyChecking=no user@your-server 'cd /path/to/your/app && git pull origin main'
